language: cpp

compiler:
    - clang
    - gcc

os:
    -Ubuntu
    -macOS

script:
    - mkdir build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=Release -Dpink_mapper_build_tests=ON ..
    - make


